server:
  port: 8081

management:
  context-path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

spring:
  rabbitmq.addresses: localhost:5672
  cloud:
    consul:
      discovery:
        healthCheckPath: ${management.context-path}/health
        healthCheckInterval: 15s
    stream.bindings.input.destination: messages

---

spring:
  profiles: test
eureka:
  client:
    enabled: false